const express=require('express'),cookieParser=require('cookie-parser'),bcrypt=require('bcryptjs'),crypto=require('crypto'),path=require('path');
const app=express();app.use(express.json());app.use(cookieParser());const PORT=process.env.PORT||10000;
const school={id:'school1',name:'Jaro-Tech Demonstration School',curriculum:'IGCSE / CBC',current_term:'Term 2',email_domain:'demo.school'};
const subjects=['Mathematics','English Language','Integrated Science','ICT','Kiswahili'].map((name,i)=>({id:'s'+i,name,code:['MAT','ENG','SCI','ICT','KIS'][i]}));
const classes=[];for(let g=7;g<=12;g++)for(const stream of ['A','B'])classes.push({class_name:'Grade '+g,stream});
const names=['Alice Chebet','Brian Kiptoo','Caroline Wanjiku','Daniel Mwangi','Esther Jepchirchir','Felix Otieno','Grace Naliaka','Henry Kibet'];
const teachers=names.map((n,i)=>({id:'t'+i,full_name:n,email:n.toLowerCase().replace(/ /g,'.')+'@demo.school',active:true,subject_id:subjects[i%5].id,class_name:'Grade '+(7+i%6),stream:i%2?'B':'A'}));
const students=[];for(let i=0;i<120;i++){let c=classes[i%12];students.push({id:'st'+i,admission_no:'DEMO-'+String(i+1).padStart(3,'0'),full_name:'Student '+String(i+1).padStart(3,'0'),class_name:c.class_name,stream:c.stream,parent_name:'Parent '+String(i+1).padStart(3,'0'),parent_email:'parent'+String(i+1).padStart(3,'0')+'@demo.school',active:true});}
const assessments=[];for(let s=0;s<5;s++)for(let j=0;j<3;j++)assessments.push({id:'a'+(s*3+j),name:['CAT 1','Mid Term','End Term'][j],term:'Term 2',max_score:100,subject_id:subjects[s].id,status:'open'});
const marks=new Map();for(const a of assessments)for(const st of students){let score=40+((st.id.charCodeAt(2)*7+a.id.charCodeAt(1)*11+Number(st.id.slice(2))*3)%61);marks.set(a.id+':'+st.id,{assessment_id:a.id,student_id:st.id,score,approved:true,locked:true,submitted_by:'demo'});}
const users=new Map(),sessions=new Map();function add(email,pw,role,name,extra={}){users.set(email,{id:crypto.randomUUID(),email,passwordHash:bcrypt.hashSync(pw,10),role,display_name:name,...extra});}
add('admin@demo.school','Admin123!','admin','Jaro-Tech Administrator');teachers.forEach(t=>add(t.email,'Teacher123!','teacher',t.full_name,{teacher_id:t.id}));for(let i=0;i<10;i++)add('parent'+String(i+1).padStart(3,'0')+'@demo.school','Parent123!','parent','Parent '+String(i+1).padStart(3,'0'),{student_ids:[students[i].id]});
function user(req){return sessions.get(req.cookies.jarotech_session)}function auth(req,res,next){req.user=user(req);if(!req.user)return res.status(401).json({error:'unauthorized',message:'Please sign in.'});next()}function roles(...r){return(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'forbidden'})}
function avg(id){let x=[];for(const m of marks.values())if(m.student_id===id){let a=assessments.find(a=>a.id===m.assessment_id);x.push(m.score/a.max_score*100)}return x.length?x.reduce((a,b)=>a+b,0)/x.length:0}function grade(p){return p>=80?'A':p>=70?'B':p>=60?'C':p>=50?'D':'E'}
app.get('/health',(q,r)=>r.json({ok:true,service:'Jaro-Tech School Management System'}));
app.post('/api/login',async(req,res)=>{let e=String(req.body.email||'').toLowerCase(),u=users.get(e);if(!u||!(await bcrypt.compare(String(req.body.password||''),u.passwordHash)))return res.status(401).json({error:'invalid_login',message:'Invalid email or password.'});let t=crypto.randomBytes(32).toString('hex');sessions.set(t,u);res.cookie('jarotech_session',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000});res.json({ok:true,user:{email:u.email,role:u.role,display_name:u.display_name}})});
app.post('/api/logout',(q,r)=>{sessions.delete(q.cookies.jarotech_session);r.clearCookie('jarotech_session');r.json({ok:true})});app.get('/api/account/me',auth,(q,r)=>r.json({email:q.user.email,role:q.user.role,display_name:q.user.display_name,school}));app.get('/api/dashboard/summary',auth,(q,r)=>r.json({students:120,teachers:8,subjects:5,role:q.user.role,school}));
app.get('/api/students/list',auth,(q,r)=>r.json({students:q.user.role==='parent'?students.filter(s=>(q.user.student_ids||[]).includes(s.id)):students}));app.get('/api/subjects/list',auth,(q,r)=>r.json(subjects));
app.get('/api/teacher/workspace',auth,roles('teacher','admin','hod'),(q,r)=>{let t=q.user.role==='teacher'?teachers.find(x=>x.id===q.user.teacher_id):teachers[0];let as=[{subject_id:t.subject_id,class_name:t.class_name,stream:t.stream}];r.json({teacher:t,school,role:q.user.role,assignments:as,subjects,assessments:assessments.filter(a=>a.subject_id===t.subject_id),students:students.filter(s=>s.class_name===t.class_name&&s.stream===t.stream)})});
app.get('/api/marks/list',auth,(q,r)=>r.json([...marks.values()].filter(m=>!q.query.assessment_id||m.assessment_id===q.query.assessment_id)));
app.post('/api/marks/bulk-save',auth,roles('teacher','admin','hod'),(q,r)=>{let a=assessments.find(a=>a.id===q.body.assessment_id),n=0;if(!a)return r.status(404).json({error:'assessment_not_found'});for(const x of q.body.rows||[]){let s=students.find(s=>s.id===x.student_id),v=Number(x.score);if(s&&v>=0&&v<=a.max_score&&!marks.get(a.id+':'+s.id)?.locked){marks.set(a.id+':'+s.id,{assessment_id:a.id,student_id:s.id,score:v,approved:false,locked:false,submitted_by:q.user.email});n++}}r.json({ok:true,saved:n})});
app.get('/api/results/overview',auth,roles('admin','hod','exam_officer'),(q,r)=>{let list=students.filter(s=>!q.query.class_name||s.class_name===q.query.class_name).map(s=>({...s,subjects:new Set([...marks.values()].filter(m=>m.student_id===s.id).map(m=>assessments.find(a=>a.id===m.assessment_id).subject_id)).size,total:[...marks.values()].filter(m=>m.student_id===s.id).reduce((a,m)=>a+m.score,0),average:avg(s.id)})).sort((a,b)=>b.average-a.average);r.json({students:list,classes:classes.map(c=>{let x=list.filter(s=>s.class_name===c.class_name&&s.stream===c.stream);return{class_name:c.class_name,stream:c.stream,students:x.length,class_average:x.length?x.reduce((a,s)=>a+s.average,0)/x.length:0}}),grades:[{grade:'A',min_score:80,max_score:100},{grade:'B',min_score:70,max_score:79.99},{grade:'C',min_score:60,max_score:69.99},{grade:'D',min_score:50,max_score:59.99},{grade:'E',min_score:0,max_score:49.99}]})});
app.get('/api/results/student',auth,(q,r)=>{let s=students.find(s=>s.id===q.query.student_id);if(!s)return r.status(404).json({error:'student_not_found'});if(q.user.role==='parent'&&!(q.user.student_ids||[]).includes(s.id))return r.status(403).json({error:'child_not_linked'});let rs=[...marks.values()].filter(m=>m.student_id===s.id&&(q.user.role!=='parent'||m.approved)).map(m=>{let a=assessments.find(a=>a.id===m.assessment_id),sub=subjects.find(s=>s.id===a.subject_id),p=m.score/a.max_score*100;return{subject_name:sub.name,assessment_name:a.name,score:m.score,max_score:a.max_score,percentage:p,grade:grade(p),remark:grade(p)==='A'?'Excellent':grade(p)==='B'?'Very Good':grade(p)==='C'?'Good':grade(p)==='D'?'Needs Improvement':'Below Standard'}});r.json({student:{...s,school_name:school.name,current_term:school.current_term},results:rs,average:rs.length?rs.reduce((a,x)=>a+x.percentage,0)/rs.length:0,scales:[{grade:'A',min_score:80,max_score:100},{grade:'B',min_score:70,max_score:79.99},{grade:'C',min_score:60,max_score:69.99},{grade:'D',min_score:50,max_score:59.99},{grade:'E',min_score:0,max_score:49.99}]})});
app.get('/api/parent/dashboard',auth,roles('parent'),(q,r)=>r.json({children:students.filter(s=>(q.user.student_ids||[]).includes(s.id)).map(s=>({id:s.id,full_name:s.full_name,admission_no:s.admission_no,class_name:s.class_name,stream:s.stream,average:avg(s.id),entries:[...marks.values()].filter(m=>m.student_id===s.id&&m.approved).length}))}));
app.get('/api/results/approval',auth,roles('admin','hod','exam_officer'),(q,r)=>{let rs=[...marks.values()].filter(m=>!q.query.assessment_id||m.assessment_id===q.query.assessment_id);r.json({submitted:rs.length,approved:rs.filter(m=>m.approved).length,rows:rs})});app.post('/api/results/approve',auth,roles('admin','hod','exam_officer'),(q,r)=>{let n=0;for(const m of marks.values())if(m.assessment_id===q.body.assessment_id){m.approved=true;m.locked=true;n++}r.json({ok:true,approved:n})});
app.get('/api/admin/teachers',auth,roles('admin','hod'),(q,r)=>r.json({teachers}));app.get('/api/admin/students',auth,roles('admin','hod'),(q,r)=>r.json({students}));app.get('/api/admin/demo-school',auth,roles('admin','hod'),(q,r)=>r.json({students:120,teachers:8,assessments:15,marks:1800}));app.get('/api/admin/demo-teachers',auth,roles('admin','hod'),(q,r)=>r.json({teachers}));app.get('/api/admin/assessments',auth,roles('admin','hod','exam_officer'),(q,r)=>r.json({assessments}));app.get('/api/admin/classes',auth,roles('admin','hod'),(q,r)=>r.json({classes}));app.get('/api/admin/structure',auth,roles('admin','hod'),(q,r)=>r.json({school,classes,subjects,teachers}));
const attendance=new Map();app.get('/api/attendance/list',auth,(q,r)=>r.json(students.map(s=>({...s,status:attendance.get(s.id+':'+q.query.date)?.status||'present',note:attendance.get(s.id+':'+q.query.date)?.note||''}))));app.post('/api/attendance/save',auth,(q,r)=>{attendance.set(q.body.student_id+':'+q.body.attendance_date,{status:q.body.status,note:q.body.note});r.json({ok:true})});
const timetable=classes.map((c,i)=>({class_name:c.class_name,stream:c.stream,day_of_week:'Monday',period_no:1,start_time:'08:00',end_time:'08:50',subject_name:subjects[i%5].name,teacher_name:teachers[i%8].full_name,room:'Room '+(i%6+1)}));app.get('/api/timetable/list',auth,(q,r)=>r.json(timetable));
app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,r)=>q.path.startsWith('/api/')?r.status(404).json({error:'route_not_found'}):r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('Jaro-Tech running on '+PORT));
